
% LU Factorization that takes into account row swapping

% Programmed by: Halfdan
%                

function [ A_out, p_out ] = LU_pivot_unb( A, p )

  [ ATL, ATR, ...
    ABL, ABR ] = FLA_Part_2x2( A, ...
                               0, 0, 'FLA_TL' );
  p = zeros(size(A,1),1)

  [ pT, ...
    pB ] = FLA_Part_2x1( p, ...
                         0, 'FLA_TOP' );

  while ( size( ATL, 1 ) < size( A, 1 ) )

    [ A00,  a01,     A02,  ...
      a10t, alpha11, a12t, ...
      A20,  a21,     A22 ] = FLA_Repart_2x2_to_3x3( ATL, ATR, ...
                                                    ABL, ABR, ...
                                                    1, 1, 'FLA_BR' );

    [ p0, ...
      pi1, ...
      p2 ] = FLA_Repart_2x1_to_3x1( pT, ...
                                    pB, ...
                                    1, 'FLA_BOTTOM' );
    %------------------------------------------------------------%
    pivotIndex = FindPivot(alpha11, a21);
    pivotABR = MakePivotMatrix(pivotIndex, ABR)*ABR;
    pivotABL = MakePivotMatrix(pivotIndex, ABL)*ABL;

    [ A00,  a01,     A02,  ...
      a10t, alpha11, a12t, ...
      A20,  a21,     A22 ] = FLA_Repart_2x2_to_3x3( ATL, ATR, ...
                                                    pivotABL, pivotABR, ...
                                                    1, 1, 'FLA_BR' );
    pi1 = pivotIndex;

    a21 = a21/alpha11;
    A22 = A22 - a21*a12t;

    %------------------------------------------------------------%

    [ ATL, ATR, ...
      ABL, ABR ] = FLA_Cont_with_3x3_to_2x2( A00,  a01,     A02,  ...
                                             a10t, alpha11, a12t, ...
                                             A20,  a21,     A22, ...
                                             'FLA_TL' );

    [ pT, ...
      pB ] = FLA_Cont_with_3x1_to_2x1( p0, ...
                                       pi1, ...
                                       p2, ...
                                       'FLA_TOP' );

  end

  A_out = [ ATL, ATR
            ABL, ABR ];

  p_out = [ pT
            pB ];

return

